# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d825b29d7f96ffe4a8529d4b2abaa327d5c922a0df7c10d302d46e0fe102ec18a32ad62c93b66e3423e3c65a1eef7b6587797a3675ac8f5974c5a1fca1cba2e

test:
  secret_key_base: 01d129e47161a4da28ff46b3d39336d4aa851c887d0d96c7419cfd8768186984e75f0b0ca0bb63c65f640dc73b3cf20c3c55b84df4397f4c1950578268c4258a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
